site_name: Podmanハンズオン
dev_addr: "0.0.0.0:8000"
nav:
    - Home: 'index.md'
    - '開始方法': 'getting-started.md'
    - 'ハンズオンコンテンツ':
        - 'Chapter 2': 'chapter2.md'
        - 'Chapter 3': 'chapter3.md'
        - 'Chapter 4': 'chapter4.md'
        - 'Chapter 5': 'chapter5.md'
        - 'Chapter 6': 'chapter6.md'
        - 'Chapter 7': 'chapter7.md'
        - 'Chapter 8': 'chapter8.md'
        - 'Chapter 9': 'chapter9.md'
        - 'Chapter 10': 'chapter10.md'
        - 'Chapter 11': 'chapter11.md'
        - 'Appendix A': 'appendixA.md'
        - 'Appendix B': 'appendixB.md'
    - '公開ポートへのアクセス方法': 'browser-access.md'
theme:
    name: material
    logo: podman.png
    palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    font:
        text: Noto Sans JP
        code: Inconsolata
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        #- navigation.indexes
        - navigation.top
        - navigation.footer
        #- content.code.copy
        - navigation.sections
plugins:
    search:
        lang: 'ja'
extra:
    social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tnk4on
      name: tnk4on on x
    - icon: fontawesome/brands/github
      link: https://github.com/tnk4on/podman-handson
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.blocks.admonition:
    - pymdownx.blocks.details:
    - pymdownx.blocks.html:
    - pymdownx.blocks.definition:
    - pymdownx.blocks.tab:
    - pymdownx.superfences:
    - pymdownx.keys
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg